# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20160523_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
    ]
