# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0005_auto_20160204_1919'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnershipOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('patronymic', models.TextField(blank=True, max_length=50, null=True)),
                ('type', models.TextField(choices=[('agent', 'Представитель агентства'), ('realtor', 'Частный агент/Риэлтор'), ('hotel_worker', 'Представитель отеля'), ('hotel_owner', 'Владелец отеля'), ('other', 'Другое')], max_length=50)),
                ('phone', models.TextField(max_length=30)),
                ('experience', models.PositiveSmallIntegerField()),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hh.City')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_partnershiporder_created_by', to='users.User')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_partnershiporder_modified_by', to='users.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patronymic', models.TextField(blank=True, max_length=50, null=True)),
                ('type', models.TextField(choices=[('agent', 'Представитель агентства'), ('realtor', 'Частный агент/Риэлтор'), ('hotel_worker', 'Представитель отеля'), ('hotel_owner', 'Владелец отеля'), ('other', 'Другое')], max_length=50)),
                ('phone', models.TextField(max_length=30)),
                ('experience', models.PositiveSmallIntegerField()),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hh.City')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
