# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160204_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnershiporder',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partnershiporder',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partnershiporder',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='partnershiporder',
            name='type',
            field=models.CharField(choices=[('agent', 'Представитель агентства'), ('realtor', 'Частный агент/Риэлтор'), ('hotel_worker', 'Представитель отеля'), ('hotel_owner', 'Владелец отеля'), ('other', 'Другое')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('agent', 'Представитель агентства'), ('realtor', 'Частный агент/Риэлтор'), ('hotel_worker', 'Представитель отеля'), ('hotel_owner', 'Владелец отеля'), ('other', 'Другое')], max_length=50),
        ),
    ]
