# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160204_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(choices=[('ooo', 'ООО'), ('zao', 'ЗАО'), ('oao', 'ОАО'), ('ip', 'ИП '), ('other', 'Другое')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_organization_created_by', to='users.User')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_organization_modified_by', to='users.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='partnershiporder',
            name='first_name',
            field=models.CharField(default='first_name', max_length=30, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnershiporder',
            name='last_name',
            field=models.CharField(default='last_name', max_length=30, verbose_name='last name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnershiporder',
            name='status',
            field=models.CharField(choices=[('new', 'Ожидает обработки'), ('in_work', 'Обрабатывается'), ('approved', 'Принята'), ('canceled', 'Отклонена')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='partnershiporder',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Organization'),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Organization'),
        ),
    ]
