# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160205_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnershiporder',
            options={'ordering': ['-created_at', 'status']},
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('ooo', 'ООО'), ('zao', 'ЗАО'), ('oao', 'ОАО'), ('ip', 'ИП '), ('other', 'Другое')], max_length=20, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='partnershiporder',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hh.City', verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='partnershiporder',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='partnershiporder',
            name='experience',
            field=models.PositiveSmallIntegerField(help_text='Опыт работы в гостиничной сфере (в годах)', verbose_name='опыт'),
        ),
        migrations.AlterField(
            model_name='partnershiporder',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Organization'),
        ),
        migrations.AlterField(
            model_name='partnershiporder',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='partnershiporder',
            name='phone',
            field=models.CharField(help_text='Ваш контактный телефон. Пример: 79251234567', max_length=30, verbose_name='Сотовый телефон'),
        ),
        migrations.AlterField(
            model_name='partnershiporder',
            name='type',
            field=models.CharField(choices=[('agent', 'Представитель агентства'), ('realtor', 'Частный агент/Риэлтор'), ('hotel_worker', 'Представитель отеля'), ('hotel_owner', 'Владелец отеля'), ('other', 'Другое')], max_length=50, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hh.City', verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.PositiveSmallIntegerField(help_text='Опыт работы в гостиничной сфере (в годах)', verbose_name='опыт'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Organization'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='отчество'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(help_text='Ваш контактный телефон. Пример: 79251234567', max_length=30, verbose_name='Сотовый телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('agent', 'Представитель агентства'), ('realtor', 'Частный агент/Риэлтор'), ('hotel_worker', 'Представитель отеля'), ('hotel_owner', 'Владелец отеля'), ('other', 'Другое')], max_length=50, verbose_name='тип'),
        ),
    ]
