# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 13:37
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160211_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnershiporder',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Ваш контактный телефон. Пример: 79251234567', max_length=30, verbose_name='Сотовый телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Ваш контактный телефон. Пример: 79251234567', max_length=30, verbose_name='Сотовый телефон'),
        ),
    ]
