# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-20 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20160323_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnershiporder',
            name='wallet_balance',
            field=models.IntegerField(default=0),
        ),
    ]
