# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-20 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_partnershiporder_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnershiporder',
            name='wallet_balance',
        ),
        migrations.AddField(
            model_name='profile',
            name='wallet_balance',
            field=models.IntegerField(default=0),
        ),
    ]
