# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 13:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20160212_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('commission', models.PositiveIntegerField(verbose_name=[django.core.validators.MaxValueValidator(100)])),
                ('agent_commission', models.PositiveIntegerField(verbose_name=[django.core.validators.MaxValueValidator(100)])),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Tariff')),
            ],
        ),
    ]
