# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 13:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_tariffelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffelement',
            name='agent_commission',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='tariffelement',
            name='commission',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
