# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20160212_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tariffelement',
            old_name='end',
            new_name='end_sum',
        ),
        migrations.RenameField(
            model_name='tariffelement',
            old_name='start',
            new_name='start_sum',
        ),
    ]
