# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 15:36
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion
import hotels.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160212_1637'),
        ('hh', '0005_auto_20160204_1919'),
        ('hotels', '0005_auto_20160212_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetroStations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=80)),
                ('color', colorful.fields.RGBColorField()),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hh.City')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels_metrostations_created_by', to='users.User')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels_metrostations_modified_by', to='users.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='tariff',
            name='is_default',
            field=models.BooleanField(default=False, validators=[hotels.models.Tariff.validate_is_default], verbose_name='Is default?'),
        ),
    ]
