# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 15:41
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_auto_20160212_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrostations',
            name='color',
            field=colorful.fields.RGBColorField(blank=True, null=True),
        ),
    ]
