# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 11:06
from __future__ import unicode_literals

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_auto_20160212_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrostation',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True),
        ),
    ]
