# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0005_auto_20160204_1919'),
        ('users', '0007_auto_20160212_1637'),
        ('hotels', '0010_auto_20160215_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', geoposition.fields.GeopositionField(blank=True, max_length=42, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('sorting', models.IntegerField(default=0)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hh.City')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels_hotel_created_by', to='users.User')),
            ],
            options={
                'permissions': (('can_search_hotels', 'Can search hotels'), ('can_book_hotels', 'Can book hotels'), ('can_send_hotel_orders', 'Can send orders to hotels')),
                'ordering': ['name', '-sorting'],
            },
        ),
        migrations.AlterModelOptions(
            name='metrostation',
            options={'ordering': ['city', 'name']},
        ),
        migrations.AddField(
            model_name='hotel',
            name='metro_stations',
            field=models.ManyToManyField(blank=True, to='hotels.MetroStation'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='modified_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels_hotel_modified_by', to='users.User'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.Tariff'),
        ),
    ]
