# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160212_1637'),
        ('hh', '0005_auto_20160204_1919'),
        ('hotels', '0011_auto_20160215_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', geoposition.fields.GeopositionField(blank=True, max_length=42, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('sorting', models.IntegerField(default=0)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hh.City')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels_property_created_by', to='users.User')),
                ('metro_stations', models.ManyToManyField(blank=True, to='hotels.MetroStation')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels_property_modified_by', to='users.User')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.Tariff')),
            ],
            options={
                'permissions': (('can_search_hotels', 'Can search property'), ('can_book_hotels', 'Can book property'), ('can_send_hotel_orders', 'Can send orders to property')),
                'ordering': ['name', '-sorting'],
            },
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='metro_stations',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='tariff',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
