# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-15 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_auto_20160215_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['name', '-sorting'], 'permissions': (('can_search_property', 'Can search property'), ('can_book_property', 'Can book property'), ('can_send_property_orders', 'Can send orders to property'))},
        ),
    ]
