# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0015_auto_20160216_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
