# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20160212_1637'),
        ('hotels', '0016_room_is_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('original', models.ImageField(upload_to='hotels_property_photos')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels_propertyphoto_created_by', to='users.User')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels_propertyphoto_modified_by', to='users.User')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
