# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 14:26
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0017_propertyphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyphoto',
            name='original',
        ),
        migrations.AddField(
            model_name='propertyphoto',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='hotels_property_photos'),
            preserve_default=False,
        ),
    ]
