# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0018_auto_20160216_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyphoto',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
