# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0019_propertyphoto_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ForeignKey(default=347, on_delete=django.db.models.deletion.PROTECT, to='hh.City'),
            preserve_default=False,
        ),
    ]
