# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 10:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0020_auto_20160218_1828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyphoto',
            options={'ordering': ['-is_default']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['price', '-name']},
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('hotel', 'отель'), ('hostel', 'хостел'), ('flat', 'квартира')], default='hotel', max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='metrostation',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True, verbose_name='coordinates'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hh.City', verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, help_text='Краткое описание отеля для поиска', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='is enabled?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='metro_stations',
            field=models.ManyToManyField(blank=True, help_text='Ближайшие станции метро', to='hotels.MetroStation', verbose_name='metro'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='property',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42, null=True, verbose_name='coordinates'),
        ),
        migrations.AlterField(
            model_name='propertyphoto',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='is default?'),
        ),
        migrations.AlterField(
            model_name='propertyphoto',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='propertyphoto',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='hotels_property_photos', verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='room',
            name='calculation_type',
            field=models.CharField(choices=[('per_person', 'За человека'), ('per_room', 'За номер')], default='per_person', max_length=20, verbose_name='calculation type'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, help_text='Краткое описание номера для поиска', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='room',
            name='gender',
            field=models.CharField(choices=[('mixed', 'Смешанный'), ('male', 'Мужской'), ('female', 'Женский')], default='mixed', max_length=20, verbose_name='room gender type'),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='is enabled?'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=255, verbose_name='room name'),
        ),
        migrations.AlterField(
            model_name='room',
            name='places',
            field=models.PositiveSmallIntegerField(help_text='Количество мест/кроватей в номере', validators=[django.core.validators.MaxValueValidator(20)], verbose_name='places'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='price'),
        ),
    ]
