# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0021_auto_20160303_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariffelement',
            options={'ordering': ['start_sum']},
        ),
    ]
