# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-20 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0022_auto_20160304_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='metro_stations',
            field=models.ManyToManyField(blank=True, help_text='Ближайшие станции метро', related_name='metro_stations', to='hotels.MetroStation', verbose_name='metro'),
        ),
    ]
