# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 11:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_auto_20160212_1637'),
        ('hotels', '0022_auto_20160304_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='first name')),
                ('patronymic', models.CharField(blank=True, max_length=50, null=True, verbose_name='patronymic')),
                ('citizenship', models.CharField(choices=[('rus', 'Россия'), ('sng', 'СНГ'), ('eu', 'Европа'), ('usa', 'США'), ('other', 'Другое')], default='rus', max_length=100, verbose_name='citizenship')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=30, verbose_name='mobile phone')),
                ('begin', models.DateField(verbose_name='Check-in')),
                ('end', models.DateField(verbose_name='Check-out')),
                ('places', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('total', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='total')),
                ('commission', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='commission')),
                ('agent_commission', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='agent commission')),
                ('is_agent_order', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('process', 'Обрабатывается'), ('completed', 'Завершена'), ('canceled', 'Отменена')], default='process', max_length=20, verbose_name='status')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('accepted_room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_accepted_room', to='hotels.Room', verbose_name='room')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_order_created_by', to='users.User')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_order_modified_by', to='users.User')),
                ('rooms', models.ManyToManyField(to='hotels.Room', verbose_name='rooms')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
