# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 12:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0022_auto_20160304_1437'),
        ('booking', '0003_auto_20160310_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='total')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='rooms',
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='total'),
        ),
        migrations.AddField(
            model_name='orderroom',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Order', verbose_name='order'),
        ),
        migrations.AddField(
            model_name='orderroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Room', verbose_name='room'),
        ),
    ]
