# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20160316_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderroom',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='is accepted'),
        ),
    ]
