# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 11:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_orderroom_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ends_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 17, 15, 3, 8, 126335), verbose_name='ends at'),
        ),
    ]
