# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 15:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_order_ends_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ends_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 17, 18, 40, 59, 20915), verbose_name='ends at'),
        ),
    ]
