# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-23 15:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20160317_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ends_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 23, 19, 8, 44, 700418), verbose_name='ends at'),
        ),
    ]
