# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-20 14:20
from __future__ import unicode_literals

import booking.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20160323_1838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderroom',
            options={'ordering': ['-is_accepted']},
        ),
        migrations.AlterField(
            model_name='order',
            name='ends_at',
            field=models.DateTimeField(default=booking.models.get_order_ends_at_datetime, verbose_name='ends at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='orderroom',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_rooms', to='booking.Order', verbose_name='order'),
        ),
    ]
