# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20160520_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('process', 'Обрабатывается'), ('completed', 'Принята'), ('canceled', 'Отменена')], default='process', max_length=20, verbose_name='status'),
        ),
    ]
