# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetreeitem',
            name='icon',
            field=models.CharField(blank=True, help_text='Иконка FontAwesome. Пример: fa-user.', max_length=50, null=True),
        ),
    ]
