# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0005_auto_20160204_1919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
    ]
